### ISSUE TITLE
Improve "Hide toolbar when scrolling"

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android#10]
I'm one of kiwix and Wikipedia readers, I'd love to be one of the the participants of the Wikipedia kiwix design team, and would like you to add this advantage of 'pocket' app to the  'kiwix' app because I love this app and want it to be the best ever.
- the advantage is when you scroll down ⬇ in the screen the app will automatically full screen so the reader will enjoy full screen reading easily without pressing on the full screen option. 
[demo.mp4.zip](https://github.com/kiwix/kiwix-android/files/802073/demo.mp4.zip)

**Comment by kelson42** [comment]
@borisfba @mhutti1 @EladKeyshawn @rashiq Any feedbacks about that idea?

**Comment by mhutti1** [comment]
@kelson42 We have already implemented this in 2.2 as a setting.

**Comment by kelson42** [comment]
@mhutti1 OK, I was not sure to 100% understand what was meant. That said this is still "only" available as an option "Hide toolbar when scrolling", not activated per default and we also have the option "fullscreen". Assuming feedbacks are good about the option "Hide toolbar when scrolling", would that make sense to make this behaviour mandatory and remove both option "fullscreen" and "Hide toolbar when scrolling" ?

**Comment by mhutti1** [comment]
@kelson42 I don't think the feature is fully ready in 2.2, other apps implement a small delay before starting the toolbar hide and I think we should also add this before possibly making it default in 2.3

**Comment by kelson42** [comment]
@mhutti1 OK, I reopen the ticket with the goal to do the improvments discussed in previous comments.

**Comment by kelson42** [comment]
@mhutti1 The option is still not set per default on 2.3. Agree to change that now.

**Comment by mhutti1** [comment]
Yes, we should make this default but allow it to be disabled in settings.

**Comment by RajaVamsi11** [comment]
@mhutti1 @kelson42  I am exicited to work in this issue as a starter.

**Comment by RajaVamsi11** [comment]
@mhutti1  What does the title  "Hide toolbar when scrolling" meant?
I am thinking that when user scrolls up ,then the toolbar must be hided or Collapsed.
Is it right?

**Comment by mhutti1** [comment]
Yes it already is implemented in our settings menu. To complete this task it must be made default but still be able to opt out in settings.

**Comment by RajaVamsi11** [comment]
It should be default and  still be able to opt out in settings! Got it

**Comment by RajaVamsi11** [comment]
@mhutti1  As you mentioned , I changed the code to make  toolbar hide when user scrolls up as default.In settings it will give an option  to enable the "Not  hide toolbar" option.By enabling it toolbar will not hide as the user scrolls up else default will work as usual( Hiding toolbar when scrolled up).
Editing code is done.can i send a PR?

**Comment by mhutti1** [comment]
@RajaVamsi11 Yeah create a PR and we will review using GitHubs interface and any changes that need to be made can be :)

**Comment by RajaVamsi11** [comment]
@mhutti1  Take a look at this one..
