### ISSUE TITLE
Search results not retrievable in wikiHow ZIMs

### ISSUE THREAD

**Issue by Inbefortus** [kiwix/kiwix-android#2768]
Example ZIM: wikiHow English 2021-10

Instead of opening, the current page is refreshed.

![Screen_Recording_20211221-125334_Kiwix_1](https://user-images.githubusercontent.com/71934042/146930760-dc83ee3b-2185-48ea-998a-5aab397ec788.gif)

**Comment by kelson42** [comment]
I strongly suspect we will have to migrate to libkiwix10 to fix this problem.

**Comment by kelson42** [comment]
@MohitMaliFtechiz This critical bug should be fixed automatically by using latest libkiwix I guess.

**Comment by MohitMaliFtechiz** [comment]
hi @kelson42 ,

The above mentioned search scenario is now working with 10.1.1 but on main page its showing now blank screen while search is working if we try to back from search result then  home page is working while on earlier version of libkiwix search is not working while home was working. 

I dig up more on this what i found is on homepage while opening first time url retrieving is ```https://kiwix.app/대문``` which is not working while when we back from search result url were ```https://kiwix.app/%EB%8C%80%EB%AC%B8``` and this is working so its URL issue on libkiwix 10.1.1 while older version its working.

**Comment by kelson42** [comment]
@MohitMaliFtechiz I guess this is redirection and it should be handled! Wonder why this is not!

**Comment by MohitMaliFtechiz** [comment]
This issue is still exist , I comment on related ticket , @kelson42 please reopen it as I have no access on libkiwix project.

**Comment by kelson42** [comment]
@MohitMaliFtechiz If you belive there is still an issue in libkiwix, please open a new ticket in kiwix/libkiwix explaining clearly (so with reproduction step) what you do, get and expect from the libkiwix.

**Comment by MohitMaliFtechiz** [comment]
https://github.com/kiwix/libkiwix/issues/824

**Comment by kelson42** [comment]
@MohitMaliFtechiz I don't understand, the ticket you point to is about the mainpage?!

**Comment by MohitMaliFtechiz** [comment]
@Inbefortus, @kelson42, This issue will be fixed after we merged https://github.com/kiwix/kiwix-android/pull/3217.


https://github.com/kiwix/kiwix-android/assets/34593983/b4b9536d-9b62-4791-be91-26c6343d9bef
