### ISSUE TITLE
Translate wiki PR failed to compile application due to ```tarask``` string file

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [kiwix/kiwix-android#3176]
**Describe the bug**
Translate wiki PR failed to compile application due to ```tarask``` string file.

Logs:-

```
ERROR:kiwix-android/app/build/intermediates/merged_res/debug/values-b+be+tarask_values-b+be+tarask.arsc.flat: AAPT: error: failed to deserialize resource table: configuration has invalid locale 'be-'.
```

**Comment by kelson42** [comment]
Any update here? What is rhe problem?

**Comment by MohitMaliFtechiz** [comment]
@kelson42 ,

* This issue is not with translate wiki. It's android AAPT(Android Asset Packaging Tool) error. Locale scripts do not support strings less than or equal to 8 bytes which is the case with ```be-tarask``` it uses 6 bytes [Issue is open on google issue tracker](https://issuetracker.google.com/issues/234820481).
* Previously we are using AGP(Android Gradle Plugin) ```4.0.1``` in that version it's working fine (no issue with AAPT). But after upgrading to ```AGP 7+``` this compilation error with AAPT(this is bug in AAPT).
* I have checked on [issue](https://issuetracker.google.com/issues/234820481) they said it will resolved in ```AGP 8.0``` .

So for now we can manually fix this error or we can right a gradle task to copy from ```values-b+be+tarask``` (if any update from TW in this file so it will be transfer to our old file) to ```values-b+be+tarask+old``` and delete the ```values-b+be+tarask``` file (for a temporary fix). After upgrading to ```AGP 8.0``` ( [Currently in alpha version](https://mvnrepository.com/artifact/com.android.tools.build/gradle?repo=google) ) we can remove this gradle task. @gouri-panda what do you think?

**Comment by kelson42** [comment]
@MohitMaliFtechiz Thank you for the explanation, will read the in upstream ticket as well.

**Comment by kelson42** [comment]
@MohitMaliFtechiz I see this bug is already more than 6 months old. How have we deal with it so far so we can keep compiling?

**Comment by kelson42** [comment]
@MohitMaliFtechiz Exceptionaly for this bug, you are allowed to modify the TW PRs when needed.... for the time being the bug is not fixed upsyream.

**Comment by MohitMaliFtechiz** [comment]
> @MohitMaliFtechiz I see this bug is already more than 6 months old. How have we deal with it so far so we can keep compiling?

hi @kelson42 , The real problem was latest gradle does not regonizse ```tarask``` so what we were doing to resolve this we are renaming it to tarask+old. We can handle it within project also by create a gradle task.

**Comment by MohitMaliFtechiz** [comment]
> @MohitMaliFtechiz Exceptionaly for this bug, you are allowed to modify the TW PRs when needed.... for the time being the bug is not fixed upsyream.

@kelson42 this is not translate wiki but its latest gralde does not recognise ```tarask```.

**Comment by kelson42** [comment]
@MohitMaliFtechiz You will still need to modify manually (making additional commits) the TW PRs.

**Comment by MohitMaliFtechiz** [comment]
@kelson42 I have one way to fix it automatically by creating gradle task which will do our job so we don't need to perform it manually. I will check this possibility.
